version: "3.8"
volumes:
  repost-archive:
    driver: local
  keycloak:
    driver: local
  db_data:

services:
  repost-archive-keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: repost-archive-keycloak
    environment:
      KC_DB: ${REPOST_ARCHIVE_KC_DB}
      KC_DB_URL: jdbc:postgresql://repost-archive-postgres-keycloak/${REPOST_ARCHIVE_KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${REPOST_ARCHIVE_KC_DB_USERNAME}
      KC_DB_USER: ${REPOST_ARCHIVE_KC_DB_USER}
      KC_DB_PASSWORD: ${REPOST_ARCHIVE_KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${REPOST_ARCHIVE_KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${REPOST_ARCHIVE_KEYCLOAK_ADMIN_PASSWORD}
      KC_LOG_LEVEL: ${REPOST_ARCHIVE_KC_LOG_LEVEL}
    command:
      - start-dev
      - --import-realm
    volumes:
      - type: bind
        source: ./keycloak/realm.json
        target: /opt/keycloak/data/import/realm.json
        read_only: true
    ports:
      - "30000:8080"
    depends_on:
      - repost-archive-postgres-keycloak
    networks:
      - repost-archive-network

  repost-archive-postgres-keycloak:
    image: postgres:latest
    container_name: repost-archive-postgres-keycloak
    volumes:
      - db_data:/var/lib/repost-archive-postgres-keycloak/data
    environment:
      POSTGRES_DB: ${REPOST_ARCHIVE_POSTGRES_DB}
      POSTGRES_USER: ${REPOST_ARCHIVE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${REPOST_ARCHIVE_POSTGRES_PASSWORD}
    networks:
      - repost-archive-network

networks:
  repost-archive-network:
    driver: bridge
