version: "3.8"
volumes:
  repost-archive:
    driver: local
  keycloak:
    driver: local
  db_data:

services:
  repost-archive-keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: repost-archive-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://repost-archive-postgres-keycloak/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_USER: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: root
      KEYCLOAK_ADMIN_PASSWORD: sudo
      KC_LOG_LEVEL: info
    command:
      - start-dev
      - --import-realm
    volumes:
      - type: bind
        source: ./home/keycloak/realm.json
        target: /opt/keycloak/data/import/realm.json
        read_only: true
    ports:
      - "30000:8080"
    depends_on:
      - repost-archive-postgres-keycloak
    networks:
      - repost-archive-network

  repost-archive-postgres-keycloak:
    image: postgres:latest
    container_name: repost-archive-postgres-keycloak
    volumes:
      - db_data:/var/lib/repost-archive-postgres-keycloak/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - repost-archive-network

networks:
  repost-archive-network:
    driver: bridge
